[build]
  publish = "."
  command = "npm run build"

[[redirects]]
  from = "/tipis"
  to = "/tipis.html"
  status = 200

[[redirects]]
  from = "/shepherd-huts"
  to = "/shepherd-huts.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/faq"
  to = "/faq.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/cookies"
  to = "/cookies.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 200

[[redirects]]
  from = "/exclusive-hire-glamping"
  to = "/exclusive-hire-glamping.html"
  status = 200

[[redirects]]
  from = "/large-group-glamping"
  to = "/large-group-glamping.html"
  status = 200

[[redirects]]
  from = "/group-glamping-hot-tub"
  to = "/group-glamping-hot-tub.html"
  status = 200

[[redirects]]
  from = "/blog/large-group-glamping-uk-guide"
  to = "/blog/large-group-glamping-uk-guide.html"
  status = 200

[[redirects]]
  from = "/exclusive-group-glamping"
  to = "/exclusive-group-glamping.html"
  status = 200

[[redirects]]
  from = "/the-tipi-retreat"
  to = "/the-tipi-retreat.html"
  status = 200

[[redirects]]
  from = "/local-guide"
  to = "/local-guide.html"
  status = 200
